- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: "Insert Environment Variable"
      include_vars:
        file: data.yaml
        name: data
   # - name: "PARSING .ENV FILE INTO LOCAL PLAYBOOK variable python script"
     # command: cat {{playbook_dir}}/.env 
    #  register: ENV   
    - name: "run app"
   #   script: helloWorld.py
      shell: python helloWorld.py
      environment: "{{  data  }}"
      register: LOGGING
    - debug: var=LOGGING.stdout

    #- name: "run my script!"
    #  command: python ./helloWorld.py
     # args:
     #   chdir: "{{ role_path }}"/files/helloWorld.py
     # delegate_to: 127.0.0.1
     # run_once: true